In [1]:
# Check two bases with linear combination to see if they are bases for R3

import numpy as np
from scipy.linalg import solve

B3 = np.array([(1, 1, 1), (1, 2, 3), (3, 5, 8)])
E3 = np.array([(1, 0, 0), (0, 1, 0), (0, 0, 1)])

def check_linear_combination(basis, target):
    try:
        coefficients = solve(basis.T, target)
        return True, coefficients
    except np.linalg.LinAlgError:
        return False, None

# Check if B3 is a basis for R3
print("Checking if B3 is a basis for R3:")
for vector in E3:
    is_combination, coeffs = check_linear_combination(B3, vector)
    if is_combination:
        print(f"{vector} is a linear combination of B3 with coefficients {coeffs}")
    else:
        print(f"{vector} is not a linear combination of B3")

# Check if E3 is a basis for R3
print("\nChecking if E3 is a basis for R3:")
for vector in B3:
    is_combination, coeffs = check_linear_combination(E3, vector)
    if is_combination:
        print(f"{vector} is a linear combination of E3 with coefficients {coeffs}")
    else:
        print(f"{vector} is not a linear combination of E3")


Checking if B3 is a basis for R3:
[1 0 0] is a linear combination of B3 with coefficients [ 1. -3.  1.]
[0 1 0] is a linear combination of B3 with coefficients [ 1.  5. -2.]
[0 0 1] is a linear combination of B3 with coefficients [-1. -2.  1.]

Checking if E3 is a basis for R3:
[1 1 1] is a linear combination of E3 with coefficients [1. 1. 1.]
[1 2 3] is a linear combination of E3 with coefficients [1. 2. 3.]
[3 5 8] is a linear combination of E3 with coefficients [3. 5. 8.]


In [2]:
# Check that B3 and E3 span R3 (i.e., are bases for R3)

print("\nChecking if B3 spans R3:")
span_B3 = all(check_linear_combination(B3, vector)[0] for vector in E3)
print(f"B3 {'spans' if span_B3 else 'does not span'} R3")

print("\nChecking if E3 spans R3:")
span_E3 = all(check_linear_combination(E3, vector)[0] for vector in B3)
print(f"E3 {'spans' if span_E3 else 'does not span'} R3")

if span_B3 and span_E3:
    print("\nBoth B3 and E3 are bases for R3")
elif span_B3:
    print("\nOnly B3 is a basis for R3")
elif span_E3:
    print("\nOnly E3 is a basis for R3")
else:
    print("\nNeither B3 nor E3 is a basis for R3")



Checking if B3 spans R3:
B3 spans R3

Checking if E3 spans R3:
E3 spans R3

Both B3 and E3 are bases for R3


In [3]:
# Represent the vector (3, -4, 6) as a linear combination of the basis vectors in E3
vector_to_represent = np.array([3, -4, 6])
is_combination, coeffs = check_linear_combination(E3, vector_to_represent)
if is_combination:
    print(f"The vector {vector_to_represent} is a linear combination of E3 with coefficients {coeffs}")
else:
    print(f"The vector {vector_to_represent} is not a linear combination of E3")


The vector [ 3 -4  6] is a linear combination of E3 with coefficients [ 3. -4.  6.]


In [4]:
# Represent the vector (3, -4, 6) as a linear combination of the basis vectors in B3.
vector_to_represent = np.array([3, -4, 6])
is_combination, coeffs = check_linear_combination(B3, vector_to_represent)
if is_combination:
    print(f"The vector {vector_to_represent} is a linear combination of B3 with coefficients {coeffs}")
else:
    print(f"The vector {vector_to_represent} is not a linear combination of B3")


The vector [ 3 -4  6] is a linear combination of B3 with coefficients [ -7. -41.  17.]


In [6]:
# Is the set B a basis for R3?

B = np.array([(-1, 2, 4), (1, 1, 1), (6, 0, -4)])

# Check if B is a basis for R3
print("\nChecking if B is a basis for R3:")
for vector in E3:
    is_combination, coeffs = check_linear_combination(B, vector)
    if is_combination:
        print(f"{vector} is a linear combination of B with coefficients {coeffs}")
    else:
        print(f"{vector} is not a linear combination of B")


Checking if B is a basis for R3:
[1 0 0] is a linear combination of B with coefficients [ 7.20575940e+15 -1.44115188e+16  3.60287970e+15]
[0 1 0] is a linear combination of B with coefficients [-1.80143985e+16  3.60287970e+16 -9.00719925e+15]
[0 0 1] is a linear combination of B with coefficients [ 1.08086391e+16 -2.16172782e+16  5.40431955e+15]


/var/folders/4c/d6mxj1_s0qzf8gdb0j1j9dsc0000gn/T/ipykernel_31874/1238804762.py:11: LinAlgWarning: Ill-conditioned matrix (rcond=1.58603e-18): result may not be accurate.
  coefficients = solve(basis.T, target)
