In [3]:
import numpy as np

# Define the matrix A
A = np.array([
    [1, 3, 1],
    [2, 0, 5],
    [4, -1, 2]
])

# Compute the inverse of matrix A
A_inverse = np.linalg.inv(A)

# Print the inverse matrix
print("The inverse of matrix A is:")
print(A_inverse)


# Compute the Reduced Row Echelon Form (RREF) of matrix A
A_rref = np.array(A, dtype=float)  # Create a copy of A as float type
n_rows, n_cols = A_rref.shape

for i in range(min(n_rows, n_cols)):
    # Find pivot
    pivot_row = i + np.argmax(np.abs(A_rref[i:, i]))
    A_rref[[i, pivot_row]] = A_rref[[pivot_row, i]]
    
    # Normalize pivot row
    A_rref[i] = A_rref[i] / A_rref[i, i]
    
    # Eliminate in other rows
    for j in range(n_rows):
        if j != i:
            A_rref[j] -= A_rref[j, i] * A_rref[i]

# Round to avoid floating point errors
A_rref = np.round(A_rref, decimals=10)

# Print the RREF of matrix A
print("\nThe Reduced Row Echelon Form (RREF) of matrix A is:")
print(A_rref)

The inverse of matrix A is:
[[ 0.09803922 -0.1372549   0.29411765]
 [ 0.31372549 -0.03921569 -0.05882353]
 [-0.03921569  0.25490196 -0.11764706]]

The Reduced Row Echelon Form (RREF) of matrix A is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# try to find the inverse of this matrix:
B = np.array([
    [2, -1, 4],
    [1, 3, 1],
    [3, -5, 7]
])

B_inverse = np.linalg.inv(B)

print("The inverse of matrix B is:")
print(B_inverse)

The inverse of matrix B is:
[[-4.18191394e+15  2.09095697e+15  2.09095697e+15]
 [ 6.43371375e+14 -3.21685688e+14 -3.21685688e+14]
 [ 2.25179981e+15 -1.12589991e+15 -1.12589991e+15]]
