In [2]:
import numpy as np

# Define the cities
cities = ['Albany', 'Boston', 'Concord', 'Durham', 'Exeter']

# Create the adjacency matrix T
T = np.array([
    [0, 1, 1, 0, 0],  # Albany
    [1, 0, 0, 1, 1],  # Boston
    [1, 0, 0, 0, 0],  # Concord
    [0, 1, 0, 0, 0],  # Durham
    [0, 1, 0, 1, 0]   # Exeter
])

# Calculate T^3
T3 = np.linalg.matrix_power(T, 3)

# Print T
print("Matrix T (adjacency matrix):")
print(T)
print()

# Print T^3
print("Matrix T^3:")
print(T3)
print()

# Answer the question
print("A passenger starts in Albany and takes three flights. They could be in:")
for i, count in enumerate(T3[0]):
    if count > 0:
        print(f"- {cities[i]} ({count} {'way' if count == 1 else 'ways'})")

Matrix T (adjacency matrix):
[[0 1 1 0 0]
 [1 0 0 1 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 1 0]]

Matrix T^3:
[[0 4 2 1 0]
 [4 1 0 3 3]
 [2 0 0 1 1]
 [0 3 1 1 0]
 [1 3 1 2 1]]

A passenger starts in Albany and takes three flights. They could be in:
- Boston (4 ways)
- Concord (2 ways)
- Durham (1 way)
