In [2]:
import numpy as np

# 1-1. Define the adjacency matrix
A = np.array([
    [0, 1, 0, 1, 0, 0, 0, 0, 0],  # Row A
    [1, 0, 1, 0, 1, 0, 0, 0, 0],  # Row B
    [0, 1, 0, 0, 0, 0, 0, 0, 0],  # Row C
    [1, 0, 0, 0, 0, 0, 1, 0, 0],  # Row D
    [0, 0, 0, 1, 0, 1, 0, 1, 0],  # Row E
    [0, 0, 1, 0, 1, 0, 0, 0, 1],  # Row F
    [0, 0, 0, 1, 0, 0, 0, 1, 0],  # Row G
    [0, 0, 0, 0, 1, 0, 0, 0, 1],  # Row H
    [0, 0, 0, 0, 0, 1, 0, 1, 0]   # Row I
])

In [5]:
# 1-2. Compute A5. Pick the smallest entry in A5 (if there is a tie, pick any one) and explain the meaning of the entry in words.
A5 = np.linalg.matrix_power(A, 5)
print(A5)

[[ 0 11  0 17  0  9  0 13  0]
 [17  0 13  0 21  0 10  0 14]
 [ 0  7  0 10  0  6  0  8  0]
 [11  0  7  0 12  0  7  0  8]
 [ 0 12  0 21  0 20  0 24  0]
 [13  0 14  0 24  0  8  0 19]
 [ 0  7  0 13  0 11  0 14  0]
 [ 9  0 11  0 20  0  6  0 17]
 [ 0  8  0 14  0 17  0 19  0]]


In [8]:
# 1-3. A person who starts at corner F is in the mood for a long walk on this grid, covering anything from 10 to 12 blocks from corner to corner.  How many different paths of length 10, 11 or 12 can the person follow to start at F and end up back at home at F?  Explain your answer in a paragraph as well as doing the appropriate calculations. 

# To find this, we can calculate A10, A11, and A12, to see how many paths of each there are at [F,F] which is the entry [6,6] in our matrix. 

# Calculate A10, A11, and A12
A10 = np.linalg.matrix_power(A, 10)
A11 = np.linalg.matrix_power(A, 11)
A12 = np.linalg.matrix_power(A, 12)

# Print the matrices to the console with labels
labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

def print_labeled_matrix(matrix, name):
    print(f"{name}:")
    print("   " + " ".join(f"{label:5}" for label in labels))
    for i, row in enumerate(matrix):
        print(f"{labels[i]:2}", end=" ")
        for value in row:
            print(f"{value:5d}", end=" ")
        print()
    print()

print_labeled_matrix(A10, "A10")
print_labeled_matrix(A11, "A11")
print_labeled_matrix(A12, "A12")

# Find the entry [6, 6] in each of these matrices to see how many paths there are of length 10, 11, and 12
# Note: We use [5,5] instead of [6,6] because Python uses 0-based indexing
print("Number of paths of length 10:", A10[5,5])
print("Number of paths of length 11:", A11[5,5])
print("Number of paths of length 12:", A12[5,5])

# Total number of paths
total_paths = A10[5,5] + A11[5,5] + A12[5,5]
print("Total number of paths:", total_paths)

A10:
   A     B     C     D     E     F     G     H     I    
A    608     0   531     0   911     0   379     0   682 
B      0   712     0  1186     0   999     0  1235     0 
C    379     0   333     0   571     0   236     0   428 
D      0   427     0   712     0   594     0   737     0 
E    911     0   847     0  1464     0   571     0  1124 
F      0   737     0  1235     0  1092     0  1330     0 
G    531     0   490     0   847     0   333     0   649 
H      0   594     0   999     0   902     0  1092     0 
I    682     0   649     0  1124     0   428     0   870 

A11:
   A     B     C     D     E     F     G     H     I    
A      0  1139     0  1898     0  1593     0  1972     0 
B   1898     0  1711     0  2946     0  1186     0  2234 
C      0   712     0  1186     0   999     0  1235     0 
D   1139     0  1021     0  1758     0   712     0  1331 
E      0  1758     0  2946     0  2588     0  3159     0 
F   1972     0  1829     0  3159     0  1235     0  2422 
G    

In [10]:
# Question 2: A superhero is at the origin of a three dimensional space.  The superhero has two devices, a hoverboard that moves any distance in the direction (1 -4  2) and a magic carpet that moves any distance in the direction (-1 3  2). 

#2-1.) An evil villain is hiding out at the point (5 -19  6).  Can the superhero catch the villain at this point?   If so, give the linear combination of the hoverboard and magic carpet vectors that bring us to the villain.

# Create the hoverboard, magic carpet, and villain vectors
hoverboard = np.array([1, -4, 2])
magic_carpet = np.array([-1, 3, 2])
villain = np.array([5, -19, 6])

# Check if there is a linear combination of hoverboard and magic carpet that equals the villain
# We need to solve the equation: a * hoverboard + b * magic_carpet = villain
# This is equivalent to solving the system of linear equations:
#   a + (-1)b = 5
#   (-4)a + 3b = -19
#   2a + 2b = 6

# We can use numpy's linalg.solve to find the solution
A = np.array([[1, -1], [-4, 3], [2, 2]])
b = np.array([5, -19, 6])

try:
    solution = np.linalg.solve(A, b)
    a, b = solution
    print(f"The superhero can catch the villain!")
    print(f"The linear combination is: {a:.2f} * hoverboard + {b:.2f} * magic_carpet")
    
    # Verify the solution
    result = a * hoverboard + b * magic_carpet
    print(f"Resulting point: {result}")
    print(f"Villain's location: {villain}")
    print(f"Difference: {np.allclose(result, villain)}")
except np.linalg.LinAlgError:
    print("The superhero cannot catch the villain at this point.")

The superhero cannot catch the villain at this point.


In [17]:
# 2-2.)  The superhero picks up a third device, a scooter.  Give a vector in R3 that the scooter could move along that would allow the superhero to reach every point in R3.

# To reach every point in R3, we need the scooter's vector to be linearly independent from the hoverboard and magic carpet vectors.
# We can choose any vector that is not in the span of the hoverboard and magic carpet vectors.

# Let's calculate the cross product of hoverboard and magic carpet vectors
scooter = np.cross(hoverboard, magic_carpet)

print("The scooter vector:", scooter)

# Verify linear independence
matrix = np.column_stack((hoverboard, magic_carpet, scooter))
rank = np.linalg.matrix_rank(matrix)

print("\nRank of the matrix formed by hoverboard, magic carpet, and scooter vectors:", rank)
if rank == 3:
    print("The scooter vector is linearly independent from the hoverboard and magic carpet vectors.")
    print("This allows the superhero to reach every point in R3.")
else:
    print("Error: The chosen vector is not linearly independent.")


The scooter vector: [-14  -4  -1]

Rank of the matrix formed by hoverboard, magic carpet, and scooter vectors: 3
The scooter vector is linearly independent from the hoverboard and magic carpet vectors.
This allows the superhero to reach every point in R3.
