In [5]:
# Over the long term estimate the percentage of all days on which the machine is totally useless, i.e., neither the copier nor scanner is working. The matrix is T = np.array([[.6, .15, .15, .1], [.05, .8, .0, .15], [1, 0, 0, 0], [1, 0, 0, 0]]). The order of the matrix is both, copier, scanner, neither, with the intersections being the percentage chance that tomorrow, let's say if both the printer and the copier are working, that tomorrow they will have a .6 chance of both being working (the intersection of both and both)
import numpy as np
# Calculate T^1000:
T = np.array([[.6, .15, .15, .1], [.05, .8, .0, .15], [1, 0, 0, 0], [1, 0, 0, 0]])
T_1000 = np.linalg.matrix_power(T, 1000)
print("T^1000 matrix:")
print(T_1000)
useless_percentage = T_1000[0, 3] * 100
print(f"The percentage of all days on which the machine is totally useless is approximately {useless_percentage:.2f}%")

T^1000 matrix:
[[0.47337278 0.35502959 0.07100592 0.10059172]
 [0.47337278 0.35502959 0.07100592 0.10059172]
 [0.47337278 0.35502959 0.07100592 0.10059172]
 [0.47337278 0.35502959 0.07100592 0.10059172]]
The percentage of all days on which the machine is totally useless is approximately 10.06%


In [4]:
# Generate a matrix in class & find the homomorphism it represents, whether that function is one-to-one or onto, and also the range space, the rank, the null space, and the nullity of the function.
import numpy as np
C = np.array([[4, -1, 5], [-3, 0, -2], [1, 4, 2], [5, -5, 5]])

In [7]:
# Find the homomorphism of C
homomorphism = lambda x, y, z: C @ np.array([x, y, z])
print("The homomorphism represented by matrix C is:")
print("f(x, y, z) =", homomorphism(1, 1, 1))  # Example evaluation

# Check if the function is one-to-one (injective)
rank = np.linalg.matrix_rank(C)
is_one_to_one = rank == C.shape[1]
print(f"Is the function one-to-one? {'Yes' if is_one_to_one else 'No'}")

# Check if the function is onto (surjective)
is_onto = rank == C.shape[0]
print(f"Is the function onto? {'Yes' if is_onto else 'No'}")

# Find the range space
range_space = np.linalg.matrix_rank(C)
print(f"The dimension of the range space is: {range_space}")

# Find the rank
print(f"The rank of the matrix is: {rank}")

# Find the null space
null_space = np.linalg.svd(C)[2][-1]
print("The null space of the matrix is:")
print(null_space)

# Find the nullity
nullity = C.shape[1] - rank
print(f"The nullity of the matrix is: {nullity}")


The homomorphism represented by matrix C is:
f(x, y, z) = [ 8 -5  7  5]
Is the function one-to-one? Yes
Is the function onto? No
The dimension of the range space is: 3
The rank of the matrix is: 3
The null space of the matrix is:
[ 0.74783603  0.10431203 -0.6556373 ]
The nullity of the matrix is: 0
