In [1]:
import numpy as np
from numpy.linalg import svd

# Define the matrix M
M = np.array([[1, 0, -1],
              [-2, 1, 4]])

# Compute the SVD
U, Sigma, Vt = svd(M)

# Task 1: Singular vectors for the columns of M
print("Matrix M:")
print(M)
print("\nLeft Singular Vectors (U):")
print(U)
print("\nSingular Values (Sigma):")
print(Sigma)
print("\nRight Singular Vectors (V^T):")
print(Vt)

# Columns of M and their geometric interpretation
print("\nColumns of M:")
for i in range(M.shape[1]):
    print(f"Column {i+1}: {M[:, i]}")

# Geometric transformation applied by V
print("\nRight Singular Vectors (V):")
for i in range(Vt.shape[1]):
    print(f"Right Singular Vector {i+1}: {Vt[:, i]}")

# Task 2: Singular vectors for the rows of M
print("\nRows of M:")
for i in range(M.shape[0]):
    print(f"Row {i+1}: {M[i, :]}")

# Geometric transformation applied by U
print("\nLeft Singular Vectors (U):")
for i in range(U.shape[1]):
    print(f"Left Singular Vector {i+1}: {U[:, i]}")


Matrix M:
[[ 1  0 -1]
 [-2  1  4]]

Left Singular Vectors (U):
[[-0.27794882  0.96059588]
 [ 0.96059588  0.27794882]]

Singular Values (Sigma):
[4.76823893 0.51370952]

Right Singular Vectors (V^T):
[[-0.46120604  0.20145716  0.86412036]
 [ 0.78779586  0.54106224  0.29432861]
 [ 0.40824829 -0.81649658  0.40824829]]

Columns of M:
Column 1: [ 1 -2]
Column 2: [0 1]
Column 3: [-1  4]

Right Singular Vectors (V):
Right Singular Vector 1: [-0.46120604  0.78779586  0.40824829]
Right Singular Vector 2: [ 0.20145716  0.54106224 -0.81649658]
Right Singular Vector 3: [0.86412036 0.29432861 0.40824829]

Rows of M:
Row 1: [ 1  0 -1]
Row 2: [-2  1  4]

Left Singular Vectors (U):
Left Singular Vector 1: [-0.27794882  0.96059588]
Left Singular Vector 2: [0.96059588 0.27794882]


In [2]:
import numpy as np
from numpy.linalg import svd

# Define the corrected matrices A and B
A = np.array([[1, 0.1],
              [2, 1.7],
              [3, 2.8],
              [4, 4.0],
              [5, 4.8],
              [6, 6.3],
              [7, 7.2],
              [8, 7.9]])

B = np.array([[1, 0.1],
              [2, 7.3],
              [3, 4.1],
              [4, 4.4],
              [5, 1.8],
              [6, 6.3],
              [7, 3.2],
              [8, 5.9]])

# Perform SVD for both matrices
U_A, Sigma_A, Vt_A = svd(A, full_matrices=False)
U_B, Sigma_B, Vt_B = svd(B, full_matrices=False)

# Print results
print("Matrix A Singular Values:")
print(Sigma_A)
print("Matrix A Right Singular Vectors (V^T):")
print(Vt_A)

print("\nMatrix B Singular Values:")
print(Sigma_B)
print("Matrix B Right Singular Vectors (V^T):")
print(Vt_B)


Matrix A Singular Values:
[20.17820726  0.74829927]
Matrix A Right Singular Vectors (V^T):
[[-0.70735021 -0.70686327]
 [-0.70686327  0.70735021]]

Matrix B Singular Values:
[18.76889335  5.40172588]
Matrix B Right Singular Vectors (V^T):
[[-0.73558635 -0.67743097]
 [ 0.67743097 -0.73558635]]


In [3]:
import numpy as np
from numpy.linalg import svd

# Define the matrix
M = np.array([[60, 29, 10],
              [52, 27, 10],
              [50, 29, 9],
              [43, 28, 10],
              [36, 27, 9]])

# Compute the SVD
U, Sigma, Vt = svd(M, full_matrices=False)

# Output results
print("Singular Values:")
print(Sigma)
print("\nFirst Singular Vector (Row Space):")
print(U[:, 0])


Singular Values:
[127.52405772   8.4371524    1.1954754 ]

First Singular Vector (Row Space):
[-0.52714128 -0.46575337 -0.45866369 -0.40913404 -0.35697734]


In [4]:
import numpy as np

# Define the grades matrix
grades = np.array([
    [60, 29, 10],  # Student A
    [52, 27, 10],  # Student B
    [50, 29, 9],   # Student C
    [43, 28, 10],  # Student D
    [36, 27, 9]    # Student E
])

# Compute the variance for each category
variances = np.var(grades, axis=0)

# Print the variances
categories = ["Exam", "Quiz", "Homework"]
for i, var in enumerate(variances):
    print(f"Variance in {categories[i]}: {var}")

# Find the category with the highest variance
max_var_index = np.argmax(variances)
print(f"\nCategory with the highest variability: {categories[max_var_index]}")


Variance in Exam: 66.55999999999999
Variance in Quiz: 0.8
Variance in Homework: 0.24

Category with the highest variability: Exam
