In [4]:
# Question 1a: Consider the matrix A = [[3, 4, -4], [4, 2, 4], [-3, -2, 4]]

# Here are 5 properties that a 3x3 matrix might have. For each we have to figure out if A has that property.

import numpy as np

# Create matrix A
A = np.array([[3, 4, -4], 
              [4, 2, 4], 
              [-3, -2, 4]])

print("Matrix A:")
print(A)

# 1. Check if rows are linearly independent
det_A = np.linalg.det(A)
print("\n1. Checking row linear independence:")
if abs(det_A) > 1e-10:  # Using small threshold to account for floating point errors
    print("TRUE: The rows are linearly independent (det(A) ≠ 0)")
else:
    print("FALSE: The rows are linearly dependent (det(A) = 0)")

# 2. Check if A is a change of basis matrix
print("\n2. Checking if A is a change of basis matrix:")
if abs(det_A) > 1e-10:
    print("TRUE: A is a change of basis matrix (det(A) ≠ 0, so A is invertible)")
else:
    print("FALSE: A is not a change of basis matrix (det(A) = 0, not invertible)")

# 3. Check if homogeneous system has multiple solutions
rank = np.linalg.matrix_rank(A)
n = A.shape[0]  # number of columns
print("\n3. Checking homogeneous system solutions:")
if rank < n:
    print("TRUE: System has multiple solutions (rank < n)")
else:
    print("FALSE: System has only trivial solution (full rank)")

# 4. Check if linear function is not one-to-one
print("\n4. Checking if linear function is not one-to-one:")
if abs(det_A) < 1e-10:
    print("TRUE: Function is not one-to-one (det(A) = 0)")
else:
    print("FALSE: Function is one-to-one (det(A) ≠ 0)")

# 5. Check if column space and row space are identical
# For a square matrix, col(A) = row(A) if and only if rank(A) = rank(A.T)
rank_A = np.linalg.matrix_rank(A)
rank_AT = np.linalg.matrix_rank(A.T)
print("\n5. Checking if column space equals row space:")
if rank_A == rank_AT and rank_A == n:
    print("TRUE: Column space and row space are identical (both = R^3)")
else:
    print("FALSE: Column space and row space are not identical")

print("\nSummary of determinant and rank:")
print(f"det(A) = {det_A:.2f}")
print(f"rank(A) = {rank}")

# Question 1b: Is the vector [2, 0, -2] an eigenvector of A? If so, find the associated eigenvalue. If not, explain how you know.

# Create the vector v
v = np.array([2, 0, -2])

# Calculate Av
Av = A @ v

# Check if Av is a scalar multiple of v
# If v is an eigenvector, then Av = λv for some scalar λ
# We can find λ by dividing any non-zero component of Av by the corresponding component of v
print("\nChecking if [2, 0, -2] is an eigenvector:")
print(f"v = {v}")
print(f"Av = {Av}")

# Find potential eigenvalue (using first non-zero component)
if v[0] != 0:
    lambda_val = Av[0]/v[0]
    print(f"\nPotential eigenvalue λ = {lambda_val}")
    
    # Check if Av = λv
    if np.allclose(Av, lambda_val * v, rtol=1e-10):
        print("YES: This is an eigenvector with eigenvalue λ =", lambda_val)
    else:
        print("NO: This is not an eigenvector because Av ≠ λv")
else:
    print("Cannot compute eigenvalue using first component (zero)")

Matrix A:
[[ 3  4 -4]
 [ 4  2  4]
 [-3 -2  4]]

1. Checking row linear independence:
TRUE: The rows are linearly independent (det(A) ≠ 0)

2. Checking if A is a change of basis matrix:
TRUE: A is a change of basis matrix (det(A) ≠ 0, so A is invertible)

3. Checking homogeneous system solutions:
FALSE: System has only trivial solution (full rank)

4. Checking if linear function is not one-to-one:
FALSE: Function is one-to-one (det(A) ≠ 0)

5. Checking if column space equals row space:
TRUE: Column space and row space are identical (both = R^3)

Summary of determinant and rank:
det(A) = -56.00
rank(A) = 3

Checking if [2, 0, -2] is an eigenvector:
v = [ 2  0 -2]
Av = [ 14   0 -14]

Potential eigenvalue λ = 7.0
YES: This is an eigenvector with eigenvalue λ = 7.0


In [5]:
# Question 2a: Find the matrices C1 and C2 containing independent columns of A1 and A2. A1 = [[1, 3, -2], [3, 9, -6], [2, 6, -4]] and A2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Define matrices A1 and A2
A1 = np.array([[1, 3, -2], [3, 9, -6], [2, 6, -4]])
A2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find rank and independent columns of A1
rank_A1 = np.linalg.matrix_rank(A1)
print("\nMatrix A1:")
print(A1)
print(f"Rank of A1: {rank_A1}")

# For A1, we can see that column 2 = 3*column 1 and column 3 = -2*column 1
# So C1 will just contain the first column
C1 = A1[:, 0:1]
print("\nIndependent columns of A1 (C1):")
print(C1)

# Find rank and independent columns of A2
rank_A2 = np.linalg.matrix_rank(A2)
print("\nMatrix A2:")
print(A2)
print(f"Rank of A2: {rank_A2}")

# For A2, we can take the first two columns as they are independent
C2 = A2[:, 0:2]
print("\nIndependent columns of A2 (C2):")
print(C2)

# Question 2b: Change just one element in matrix A2 to make a new matrix, B, so that when we factor B into C*R the matrix R is the 3x3 identity matrix.

# To get R as identity matrix, B needs to have linearly independent columns
# We can modify A2[2,2] (the bottom-right element) to 10 to achieve this
B = A2.copy()
B[2,2] = 10
print("\nModified matrix B:")
print(B)

# Verify that columns are now independent
rank_B = np.linalg.matrix_rank(B)
print(f"Rank of B: {rank_B}")

# Question 3c: Explain in a sentence why we could not change just one element in A1 that would make R the 3x3 identity. 
print("\nAnswer to 2c: We cannot fix A1 with one change because it has proportional columns (column 2 is 3 times column 1 and column 3 is -2 times column 1), so changing any single element would not break these proportional relationships for all elements.")


Matrix A1:
[[ 1  3 -2]
 [ 3  9 -6]
 [ 2  6 -4]]
Rank of A1: 1

Independent columns of A1 (C1):
[[1]
 [3]
 [2]]

Matrix A2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of A2: 2

Independent columns of A2 (C2):
[[1 2]
 [4 5]
 [7 8]]

Modified matrix B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
Rank of B: 3

Answer to 2c: We cannot fix A1 with one change because it has proportional columns (column 2 is 3 times column 1 and column 3 is -2 times column 1), so changing any single element would not break these proportional relationships for all elements.


In [8]:
# Question 3: A small local bakery categorizes purchases by customers into three distinct groups: prepared foods (sandwiches, soups, etc), baked goods (breads, cookies, cakes, etc.) and beverages. At lunch time today we monitored seven customers who made phone orders. The data for how much money each person spent on each menu groups is recorded in a matrix A. The first row of 34.35 0 25.29 means that the customer spent $34.35 on prepared foods, $0 on baked goods, and $25.29 on beverages.

# Create matrix A
A = np.array([[34.35, 0, 25.29], 
              [39.5, 0, 2.59], 
              [11.17, 0, 0], 
              [0, 26.5, 12.4], 
              [14.07, 24.20, 0], 
              [48.22, 11.69, 15.15], 
              [80.45, 0, 0]])

# Question 3a: Find singular values
singular_values = np.linalg.svd(A)[1]
print("\nSingular values of A:")
print(singular_values)
print("\nInterpretation: The first singular value is much larger than the others, indicating that")
print("most of the variation in the data can be captured by a single dimension/pattern.")

# Question 3b: Get first right singular vector
_, _, Vt = np.linalg.svd(A)
first_singular_vector = Vt[0]
print("\nFirst singular vector (row space):")
print(first_singular_vector)
print("\nInterpretation: This vector shows the relative importance of each category.")
print("The largest component corresponds to prepared foods, showing it's the dominant category.")

# Question 3c: Replace last row with more typical values and recompute
A_modified = A.copy()
# Replace last row with values more similar to other customers
A_modified[-1] = [35.0, 12.5, 10.0]  # More typical values

new_singular_values = np.linalg.svd(A_modified)[1]
print("\nNew singular values after modification:")
print(new_singular_values)
print("\nInterpretation: After replacing the outlier values, the singular values are more")
print("balanced, indicating more even distribution of spending patterns across categories.")


Singular values of A:
[110.49308753  38.89249694  24.35260333]

Interpretation: The first singular value is much larger than the others, indicating that
most of the variation in the data can be captured by a single dimension/pattern.

First singular vector (row space):
[-0.98401537 -0.08971724 -0.15383294]

Interpretation: This vector shows the relative importance of each category.
The largest component corresponds to prepared foods, showing it's the dominant category.

New singular values after modification:
[87.48051861 35.48788944 20.27841381]

Interpretation: After replacing the outlier values, the singular values are more
balanced, indicating more even distribution of spending patterns across categories.
